### ISSUE TITLE
Plugin crashing upon beginning task context

### ISSUE THREAD

**Issue by fairlight1337** [code-iai/sr_plugin_knowrob#3]
The plugin (and semrec) crashes when a context is begun.

**Comment by fairlight1337** [comment]
@airballking 

Fixed in https://github.com/code-iai/sr_plugin_knowrob/commit/2a35c67dd3179fca2a2ef6b1122c521ecee6a29f.

**Comment by airballking** [comment]
@fairlight1337 Just checked out your fix. The plugin compiles, starts, and survives my simple little test. I could also query for my asserted detection events. So, everything looks fine now. I'll keep you posted on the behavior as I build my application.

Thanks for the quick fix!
